/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Sched_App_GUI;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Insets;
import java.awt.Event;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import static javafx.scene.paint.Color.rgb;
import javax.swing.BorderFactory;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;


/**
 *
 * @author Calvin
 */
public class SchedAppGUI extends javax.swing.JApplet {
    
    
    JCheckBox[][] TakenMasterList = new JCheckBox[4][6];
    JPanel[][] ColorPanelMasterList = new JPanel[4][6];
    int row;
    int col;
    SchedTreeManager GloriousCreator = new SchedTreeManager();

    /**
     * Initializes the applet SchedAppGUI
     */
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchedAppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchedAppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchedAppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchedAppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        setBackground(new java.awt.Color(150,150,150));
        resize(1100,650);
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SelectMajorComboBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        SchedTreePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ElectivesPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CourseTypeComboBox = new javax.swing.JComboBox();
        CourseTypeComboBox1 = new javax.swing.JComboBox();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1100, 600));
        setMinimumSize(new java.awt.Dimension(1100, 600));
        setPreferredSize(new java.awt.Dimension(1100, 600));

        SelectMajorComboBox.setBackground(new java.awt.Color(150, 150, 150));
        SelectMajorComboBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SelectMajorComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select a Major", "Computer Science", "Chemistry", "Physics", "Biology", "Mathematics" }));
        SelectMajorComboBox.setMaximumSize(new java.awt.Dimension(153, 23));
        SelectMajorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectMajorComboBoxActionPerformed(evt);
            }
        });

        SchedTreePanel.setBackground(new java.awt.Color(100, 0, 100));
        SchedTreePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        SchedTreePanel.setAutoscrolls(true);
        SchedTreePanel.setMaximumSize(new java.awt.Dimension(1500, 800));
        SchedTreePanel.setMinimumSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout SchedTreePanelLayout = new javax.swing.GroupLayout(SchedTreePanel);
        SchedTreePanel.setLayout(SchedTreePanelLayout);
        SchedTreePanelLayout.setHorizontalGroup(
            SchedTreePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        SchedTreePanelLayout.setVerticalGroup(
            SchedTreePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(SchedTreePanel);

        ElectivesPanel.setBackground(new java.awt.Color(230, 230, 230));
        ElectivesPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ElectivesPanel.setAutoscrolls(true);
        ElectivesPanel.setMaximumSize(new java.awt.Dimension(1000, 134));
        ElectivesPanel.setMinimumSize(new java.awt.Dimension(500, 134));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setText("Electives:");

        javax.swing.GroupLayout ElectivesPanelLayout = new javax.swing.GroupLayout(ElectivesPanel);
        ElectivesPanel.setLayout(ElectivesPanelLayout);
        ElectivesPanelLayout.setHorizontalGroup(
            ElectivesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ElectivesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(1126, Short.MAX_VALUE))
        );
        ElectivesPanelLayout.setVerticalGroup(
            ElectivesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ElectivesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(ElectivesPanel);

        CourseTypeComboBox.setBackground(new java.awt.Color(150, 150, 150));
        CourseTypeComboBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CourseTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Major Courses", "Science Courses", "Gen Ed Courses" }));

        CourseTypeComboBox1.setBackground(new java.awt.Color(150, 150, 150));
        CourseTypeComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CourseTypeComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Panel View", "Table View", "List View" }));
        CourseTypeComboBox1.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SelectMajorComboBox, 0, 169, Short.MAX_VALUE)
                    .addComponent(CourseTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CourseTypeComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(SelectMajorComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CourseTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CourseTypeComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SelectMajorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectMajorComboBoxActionPerformed
        Course[]CourseList;
        CourseList = new Course[24];
       
        Course Test = new Course(1470, 4, "Computer Science I", "CSCI", "Always");
        Course comp = new Course(1480, 4, "Computer Science II", "CSCI", "Always", "CSCI 1470 Computer Science I");
        CourseList[0] = Test;
        CourseList[1] = comp;
        comp = new Course(2320, 3, "Data Structures", "CSCI", "Always", "CSCI 1480 Computer Science II");
        CourseList[6] = comp;
        comp = new Course(2440, 3, "Assembly Language", "CSCI", "Always", "CSCI 1480 Computer Science II");
        CourseList[7] = comp;
        comp = new Course(3190, 1, "Social Implications", "CSCI", "Fall", "CSCI 2320 Data Structures");
        CourseList[12] = comp;
        comp = new Course(3330, 3, "Algorithms", "CSCI", "Always", "CSCI 2320 Data Structures");
        CourseList[13] = comp;
        comp = new Course(3360, 3, "Database Systems", "CSCI", "Fall", "CSCI 2320 Data Structures");
        CourseList[14] = comp;
        comp = new Course(3370, 3, "Principles of Program", "CSCI", "Spring", "CSCI 2320 Data Structures");
        CourseList[15] = comp;
        comp = new Course(3380, 3, "Computer Architecture", "CSCI", "Spring", "CSCI 2440 Assembly Language");
        CourseList[16] = comp;
        comp = new Course(3381, 4, "Java", "CSCI","Spring", "CSCI 2320 Data Structures");
        CourseList[17] = comp;
        comp = new Course(4191, 1, "Seminar", "CSCI", "Spring");
        CourseList[18] = comp;
        comp = new Course(4300, 3, "Operating Systems", "CSCI", "Spring", "CSCI 3330 Algorithms", "CSCI 3380 Computer Architecture");
        CourseList[19] = comp;
        comp = new Course(4490, 3, "Software Engineering", "CSCI", "Always", "CSCI 3381 Java");
        
        SchedTreePanel.removeAll();
        GloriousCreator.TreeCreation(CourseList, SchedTreePanel, ElectivesPanel);
    }//GEN-LAST:event_SelectMajorComboBoxActionPerformed
        
    public static void changeFont ( Component component, Font font ){
        component.setFont ( font );
        if ( component instanceof Container )
        {
            for ( Component child : ( ( Container ) component ).getComponents () )
            {
                changeFont ( child, font );
         }
    }
}
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CourseTypeComboBox;
    private javax.swing.JComboBox CourseTypeComboBox1;
    private javax.swing.JPanel ElectivesPanel;
    private javax.swing.JPanel SchedTreePanel;
    private javax.swing.JComboBox SelectMajorComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
