/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sched_App_GUI;

/**
 *
 * @author Calvin
 */
public class YearPlanner extends javax.swing.JFrame {

    /**
     * Creates new form YearPlanner
     */
    public YearPlanner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClassesPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        SemScrollPanel = new javax.swing.JScrollPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        jSplitPane3 = new javax.swing.JSplitPane();
        jSplitPane4 = new javax.swing.JSplitPane();
        jSplitPane5 = new javax.swing.JSplitPane();
        jSplitPane6 = new javax.swing.JSplitPane();
        jSplitPane7 = new javax.swing.JSplitPane();
        jSplitPane8 = new javax.swing.JSplitPane();
        jSplitPane9 = new javax.swing.JSplitPane();
        jSplitPane10 = new javax.swing.JSplitPane();
        jSplitPane11 = new javax.swing.JSplitPane();
        SemPanel11 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        SemPanel12 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        SemPanel10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        SemPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        SemPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        SemPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        SemPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        SemPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        SemPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        SemPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        SemPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        SemPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(175, 175, 175));

        ClassesPanel.setBackground(new java.awt.Color(255, 255, 255));
        ClassesPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setText("Classes:");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pick a Department", "Computer Science", "Mathematics", "Biology", "Chemistry", "Physics" }));

        javax.swing.GroupLayout ClassesPanelLayout = new javax.swing.GroupLayout(ClassesPanel);
        ClassesPanel.setLayout(ClassesPanelLayout);
        ClassesPanelLayout.setHorizontalGroup(
            ClassesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClassesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        ClassesPanelLayout.setVerticalGroup(
            ClassesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClassesPanelLayout.createSequentialGroup()
                .addGroup(ClassesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(280, Short.MAX_VALUE))
        );

        SemScrollPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        SemScrollPanel.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        SemScrollPanel.setMaximumSize(new java.awt.Dimension(327670, 327670));
        SemScrollPanel.setMinimumSize(new java.awt.Dimension(4000, 620));
        SemScrollPanel.setPreferredSize(new java.awt.Dimension(1220, 620));

        jSplitPane1.setDividerLocation(300);

        jSplitPane2.setDividerLocation(300);

        jSplitPane3.setDividerLocation(300);

        jSplitPane6.setLastDividerLocation(300);

        jSplitPane9.setDividerLocation(300);
        jSplitPane9.setMaximumSize(new java.awt.Dimension(1221, 566));

        jSplitPane10.setDividerLocation(300);
        jSplitPane10.setMaximumSize(new java.awt.Dimension(914, 564));

        jSplitPane11.setDividerLocation(300);
        jSplitPane11.setMaximumSize(new java.awt.Dimension(607, 562));

        SemPanel11.setBackground(new java.awt.Color(150, 0, 150));
        SemPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SemPanel11.setMaximumSize(new java.awt.Dimension(300, 560));
        SemPanel11.setMinimumSize(new java.awt.Dimension(300, 560));
        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWidths = new int[] {1};
        jPanel3Layout.rowHeights = new int[] {1};
        jPanel3Layout.columnWeights = new double[] {1.0};
        jPanel3Layout.rowWeights = new double[] {1.0};
        SemPanel11.setLayout(jPanel3Layout);

        jLabel12.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Semester 11");
        SemPanel11.add(jLabel12, new java.awt.GridBagConstraints());

        jSplitPane11.setLeftComponent(SemPanel11);

        SemPanel12.setBackground(new java.awt.Color(200, 200, 200));
        SemPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SemPanel12.setMaximumSize(new java.awt.Dimension(300, 560));
        SemPanel12.setMinimumSize(new java.awt.Dimension(300, 560));
        SemPanel12.setPreferredSize(new java.awt.Dimension(300, 560));
        java.awt.GridBagLayout jPanel10Layout = new java.awt.GridBagLayout();
        jPanel10Layout.columnWidths = new int[] {1};
        jPanel10Layout.rowHeights = new int[] {1};
        jPanel10Layout.columnWeights = new double[] {1.0};
        jPanel10Layout.rowWeights = new double[] {1.0};
        SemPanel12.setLayout(jPanel10Layout);

        jLabel13.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Semester 12");
        SemPanel12.add(jLabel13, new java.awt.GridBagConstraints());

        jSplitPane11.setRightComponent(SemPanel12);

        jSplitPane10.setRightComponent(jSplitPane11);

        SemPanel10.setBackground(new java.awt.Color(200, 200, 200));
        SemPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SemPanel10.setMaximumSize(new java.awt.Dimension(300, 560));
        SemPanel10.setMinimumSize(new java.awt.Dimension(300, 560));
        SemPanel10.setPreferredSize(new java.awt.Dimension(300, 560));
        java.awt.GridBagLayout jPanel11Layout = new java.awt.GridBagLayout();
        jPanel11Layout.columnWidths = new int[] {1};
        jPanel11Layout.rowHeights = new int[] {1};
        jPanel11Layout.columnWeights = new double[] {1.0};
        jPanel11Layout.rowWeights = new double[] {1.0};
        SemPanel10.setLayout(jPanel11Layout);

        jLabel11.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Semester 10");
        SemPanel10.add(jLabel11, new java.awt.GridBagConstraints());

        jSplitPane10.setLeftComponent(SemPanel10);

        jSplitPane9.setRightComponent(jSplitPane10);

        SemPanel9.setBackground(new java.awt.Color(150, 0, 150));
        SemPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SemPanel9.setMaximumSize(new java.awt.Dimension(300, 560));
        SemPanel9.setMinimumSize(new java.awt.Dimension(300, 560));
        SemPanel9.setPreferredSize(new java.awt.Dimension(300, 560));
        java.awt.GridBagLayout jPanel6Layout = new java.awt.GridBagLayout();
        jPanel6Layout.columnWidths = new int[] {1};
        jPanel6Layout.rowHeights = new int[] {1};
        jPanel6Layout.columnWeights = new double[] {1.0};
        jPanel6Layout.rowWeights = new double[] {1.0};
        SemPanel9.setLayout(jPanel6Layout);

        jLabel10.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Semester 9");
        SemPanel9.add(jLabel10, new java.awt.GridBagConstraints());

        jSplitPane9.setLeftComponent(SemPanel9);

        jSplitPane8.setRightComponent(jSplitPane9);

        SemPanel8.setBackground(new java.awt.Color(200, 200, 200));
        SemPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SemPanel8.setMaximumSize(new java.awt.Dimension(300, 560));
        SemPanel8.setMinimumSize(new java.awt.Dimension(300, 560));
        SemPanel8.setPreferredSize(new java.awt.Dimension(300, 560));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {1};
        jPanel1Layout.rowHeights = new int[] {1};
        jPanel1Layout.columnWeights = new double[] {1.0};
        jPanel1Layout.rowWeights = new double[] {1.0};
        SemPanel8.setLayout(jPanel1Layout);

        jLabel9.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Semester 8");
        SemPanel8.add(jLabel9, new java.awt.GridBagConstraints());

        jSplitPane8.setLeftComponent(SemPanel8);

        jSplitPane7.setRightComponent(jSplitPane8);

        SemPanel7.setBackground(new java.awt.Color(150, 0, 150));
        SemPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SemPanel7.setMaximumSize(new java.awt.Dimension(300, 560));
        SemPanel7.setMinimumSize(new java.awt.Dimension(300, 560));
        SemPanel7.setPreferredSize(new java.awt.Dimension(300, 560));
        java.awt.GridBagLayout jPanel8Layout = new java.awt.GridBagLayout();
        jPanel8Layout.columnWidths = new int[] {1};
        jPanel8Layout.rowHeights = new int[] {1};
        jPanel8Layout.columnWeights = new double[] {1.0};
        jPanel8Layout.rowWeights = new double[] {1.0};
        SemPanel7.setLayout(jPanel8Layout);

        jLabel8.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Semester 7");
        jLabel8.setToolTipText("");
        SemPanel7.add(jLabel8, new java.awt.GridBagConstraints());

        jSplitPane7.setLeftComponent(SemPanel7);

        jSplitPane6.setRightComponent(jSplitPane7);

        SemPanel6.setBackground(new java.awt.Color(200, 200, 200));
        SemPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SemPanel6.setMaximumSize(new java.awt.Dimension(300, 560));
        SemPanel6.setMinimumSize(new java.awt.Dimension(300, 560));
        SemPanel6.setPreferredSize(new java.awt.Dimension(300, 560));
        java.awt.GridBagLayout jPanel12Layout = new java.awt.GridBagLayout();
        jPanel12Layout.columnWidths = new int[] {1};
        jPanel12Layout.rowHeights = new int[] {1};
        jPanel12Layout.columnWeights = new double[] {1.0};
        jPanel12Layout.rowWeights = new double[] {1.0};
        SemPanel6.setLayout(jPanel12Layout);

        jLabel7.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Semester 6");
        SemPanel6.add(jLabel7, new java.awt.GridBagConstraints());

        jSplitPane6.setLeftComponent(SemPanel6);

        jSplitPane5.setRightComponent(jSplitPane6);

        SemPanel5.setBackground(new java.awt.Color(150, 0, 150));
        SemPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SemPanel5.setMaximumSize(new java.awt.Dimension(300, 560));
        SemPanel5.setMinimumSize(new java.awt.Dimension(300, 560));
        SemPanel5.setPreferredSize(new java.awt.Dimension(300, 560));
        java.awt.GridBagLayout jPanel9Layout = new java.awt.GridBagLayout();
        jPanel9Layout.columnWidths = new int[] {1};
        jPanel9Layout.rowHeights = new int[] {8};
        jPanel9Layout.columnWeights = new double[] {1.0};
        jPanel9Layout.rowWeights = new double[] {1.0};
        SemPanel5.setLayout(jPanel9Layout);

        jLabel6.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Semester 5");
        SemPanel5.add(jLabel6, new java.awt.GridBagConstraints());

        jSplitPane5.setLeftComponent(SemPanel5);

        jSplitPane4.setRightComponent(jSplitPane5);

        SemPanel4.setBackground(new java.awt.Color(200, 200, 200));
        SemPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SemPanel4.setMaximumSize(new java.awt.Dimension(300, 560));
        SemPanel4.setMinimumSize(new java.awt.Dimension(300, 560));
        SemPanel4.setPreferredSize(new java.awt.Dimension(300, 560));
        java.awt.GridBagLayout jPanel13Layout = new java.awt.GridBagLayout();
        jPanel13Layout.columnWidths = new int[] {1};
        jPanel13Layout.rowHeights = new int[] {1};
        jPanel13Layout.columnWeights = new double[] {1.0};
        jPanel13Layout.rowWeights = new double[] {1.0};
        SemPanel4.setLayout(jPanel13Layout);

        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Semester 4");
        SemPanel4.add(jLabel5, new java.awt.GridBagConstraints());

        jSplitPane4.setLeftComponent(SemPanel4);

        jSplitPane3.setRightComponent(jSplitPane4);

        SemPanel3.setBackground(new java.awt.Color(150, 0, 150));
        SemPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SemPanel3.setMaximumSize(new java.awt.Dimension(300, 560));
        SemPanel3.setMinimumSize(new java.awt.Dimension(300, 560));
        SemPanel3.setPreferredSize(new java.awt.Dimension(300, 560));
        java.awt.GridBagLayout jPanel7Layout = new java.awt.GridBagLayout();
        jPanel7Layout.columnWidths = new int[] {1};
        jPanel7Layout.rowHeights = new int[] {1};
        jPanel7Layout.columnWeights = new double[] {1.0};
        jPanel7Layout.rowWeights = new double[] {1.0};
        SemPanel3.setLayout(jPanel7Layout);

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Semester 3");
        SemPanel3.add(jLabel4, new java.awt.GridBagConstraints());

        jSplitPane3.setLeftComponent(SemPanel3);

        jSplitPane2.setRightComponent(jSplitPane3);

        SemPanel2.setBackground(new java.awt.Color(200, 200, 200));
        SemPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SemPanel2.setMaximumSize(new java.awt.Dimension(300, 560));
        SemPanel2.setMinimumSize(new java.awt.Dimension(300, 560));
        SemPanel2.setPreferredSize(new java.awt.Dimension(300, 560));
        java.awt.GridBagLayout jPanel4Layout = new java.awt.GridBagLayout();
        jPanel4Layout.columnWidths = new int[] {1};
        jPanel4Layout.rowHeights = new int[] {1};
        jPanel4Layout.columnWeights = new double[] {1.0};
        jPanel4Layout.rowWeights = new double[] {1.0};
        SemPanel2.setLayout(jPanel4Layout);

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Semester 2");
        SemPanel2.add(jLabel3, new java.awt.GridBagConstraints());

        jSplitPane2.setLeftComponent(SemPanel2);

        jSplitPane1.setRightComponent(jSplitPane2);

        SemPanel1.setBackground(new java.awt.Color(150, 0, 150));
        SemPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SemPanel1.setMaximumSize(new java.awt.Dimension(300, 560));
        SemPanel1.setMinimumSize(new java.awt.Dimension(300, 560));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {1};
        jPanel2Layout.rowHeights = new int[] {1};
        jPanel2Layout.columnWeights = new double[] {1.0};
        jPanel2Layout.rowWeights = new double[] {1.0};
        SemPanel1.setLayout(jPanel2Layout);

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Semester 1");
        SemPanel1.add(jLabel2, new java.awt.GridBagConstraints());

        jSplitPane1.setLeftComponent(SemPanel1);

        SemScrollPanel.setViewportView(jSplitPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SemScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1229, Short.MAX_VALUE)
                    .addComponent(ClassesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SemScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClassesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YearPlanner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YearPlanner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YearPlanner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YearPlanner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YearPlanner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ClassesPanel;
    private javax.swing.JPanel SemPanel1;
    private javax.swing.JPanel SemPanel10;
    private javax.swing.JPanel SemPanel11;
    private javax.swing.JPanel SemPanel12;
    private javax.swing.JPanel SemPanel2;
    private javax.swing.JPanel SemPanel3;
    private javax.swing.JPanel SemPanel4;
    private javax.swing.JPanel SemPanel5;
    private javax.swing.JPanel SemPanel6;
    private javax.swing.JPanel SemPanel7;
    private javax.swing.JPanel SemPanel8;
    private javax.swing.JPanel SemPanel9;
    private javax.swing.JScrollPane SemScrollPanel;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane10;
    private javax.swing.JSplitPane jSplitPane11;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JSplitPane jSplitPane5;
    private javax.swing.JSplitPane jSplitPane6;
    private javax.swing.JSplitPane jSplitPane7;
    private javax.swing.JSplitPane jSplitPane8;
    private javax.swing.JSplitPane jSplitPane9;
    // End of variables declaration//GEN-END:variables
}
