/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import java.io.*;
import java.util.*;
import javax.swing.*;
import javax.swing.JTable;
import java.awt.event.*;
/**
 *
 * @author Justin
 */
public class ErrorLogInterface{

	private boolean running = true;
	private int nextViewID = 2;
    /**
     * Creates new form ErrorLogInterface
     */
    public ErrorLogInterface() {


        
        //populate gui field with info from the database
        
    }
    
    private void createTable(){
        //TODO replace with real database info
        Scanner testIn = null;
        
        //TODO database connection here
        try{
            File testfile = new File("C:\\Users\\Justin\\Desktop\\Course Scheduler\\Course_Scheduler\\CourseSchedApp_v3.0.1\\errorTest.txt");
            testIn = new Scanner(testfile);
        }
        catch(FileNotFoundException e){
            System.out.print("File Not Found...");
        }
        
        //initialize column counter
        int rows = 0;
        
        //initial table data
        Object tableData[][] = new Object[3][4];
        
        while(testIn.hasNext()){
            //store data
            String testLine[] = testIn.nextLine().split(",");
            //populate the row with error data
            tableData[rows][0] = testLine[0];
            tableData[rows][1] = testLine[1];
            tableData[rows][2] = testLine[2];
            tableData[rows][3] = testLine[3];
            //set a status combobox in every row
            rows++;
        }
        
        //create table
        ErrorLog = new JTable(rows, 4);/*{
            @Override
             public String getToolTipText( MouseEvent e )
            {
                int row = rowAtPoint( e.getPoint() );
                int column = columnAtPoint( e.getPoint() );

                Object value = getValueAt(row, column);
                return value == null ? null : value.toString();
            }
            
        };*/
        //set Table font
        ErrorLog.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        
        //set Table Model
        ErrorLog.setModel(new javax.swing.table.DefaultTableModel(
            tableData,
            new String [] {
                "ID", "Description", "Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        
        //setRowHeight
        ErrorLog.setRowHeight(50);
        mainPanel.add(ErrorLog);
    }
    
    private void getErrorData(int max_rows){
        createTable();
        //add Component to GUI
        //ErrorLog_ScrollPanel.setViewportView(ErrorLog);
        
        //set each row's editor to the ErrorLogStatus ComboBox
        ErrorLog.getColumnModel().getColumn(3).setCellEditor(new DefaultCellEditor(errorLogStatus));
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
/*
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1197, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1049, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
*/
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    public void initComponents(JPanel mainPanel) {
    	/*
        jPanel1 = new JPanel();
        ErrorLog_Title = new JLabel();
        ErrorLog_ScrollPanel = new JScrollPane();
        ScrollContainer_Panel = new JPanel();
        
        //create submit button with action listener
        ErrorLog_SubmitButton = new javax.swing.JToggleButton();

        ErrorLog_SubmitButton.setText("Submit");
        
        //adding anonymous inner action listener
        ErrorLog_SubmitButton.addActionListener(new ActionListener(){
        
            @Override
            public void actionPerformed(ActionEvent event){
                //TODO button action
                System.out.println("Submit Pressed");
            }
        });
        
        ErrorLog_Title.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        ErrorLog_Title.setText("Error Log");

        //TODO better layout management
        javax.swing.GroupLayout ScrollContainer_PanelLayout = new javax.swing.GroupLayout(ScrollContainer_Panel);
        ScrollContainer_Panel.setLayout(ScrollContainer_PanelLayout);
        ScrollContainer_PanelLayout.setHorizontalGroup(
            ScrollContainer_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        ScrollContainer_PanelLayout.setVerticalGroup(
            ScrollContainer_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );
        
        //add everything to mainPanel in main applet
        this.mainPanel.add(ScrollContainer_Panel);
        
        //add scroll panel to the JPanel
        ErrorLog_ScrollPanel.setViewportView(ScrollContainer_Panel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ErrorLog_ScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ErrorLog_Title)
                        .addGap(494, 494, 494))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ErrorLog_SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(ErrorLog_Title)
                .addGap(18, 18, 18)
                .addComponent(ErrorLog_ScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ErrorLog_SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
*/
        //initialize status selection categories
        errorLogStatus.addItem("New");
        errorLogStatus.addItem("Updated");
        errorLogStatus.addItem("Reviewing");
        errorLogStatus.addItem("Solved");

        this.mainPanel = mainPanel;
    	getErrorData(20); 
    	mainPanel.repaint();
        
    }          
             

    public int checkCurrentViewID() {
    	return nextViewID;
    }
    
    private JButton returnButton = new JButton("Return");
    private JPanel mainPanel;
    private javax.swing.JTable ErrorLog;
    private JComboBox errorLogStatus = new JComboBox();
    /* 
       // Variables declaration - do not modify                     
    private javax.swing.JScrollPane ErrorLog_ScrollPanel;
    private javax.swing.JToggleButton ErrorLog_SubmitButton;
    private javax.swing.JLabel ErrorLog_Title;
    private javax.swing.JPanel ScrollContainer_Panel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}*/
}